rack_pr24:
  base_path: /srv/fast/comfyui-models
  checkpoints: checkpoints
  configs: configs
  diffusion_models: |
    diffusion_models
    unet
  text_encoders: |
    text_encoders
    clip
  vae: vae
  vae_approx: vae_approx
  loras: loras
  embeddings: embeddings
  controlnet: controlnet
  clip_vision: clip_vision
  ipadapter: ipadapter
  upscale_models: upscale_models
  latent_upscale_models: latent_upscale_models
  style_models: style_models
  diffusers: diffusers
  gligen: gligen
  hypernetworks: hypernetworks
  photomaker: photomaker
  model_patches: model_patches
  audio_encoders: audio_encoders
  background_removal: background_removal
  frame_interpolation: frame_interpolation
  geometry_estimation: geometry_estimation
  optical_flow: optical_flow
  detection: detection
